//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyDiary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyDiary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circle {
            get {
                object obj = ResourceManager.GetObject("circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACEAAAAhCAIAAADYhlU4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADgSURBVEhLvY1ZEsMgFMNy/0u3jcSUkiFhe1RfLLZ8/InXTvJGOkWzd0Pnxo2PUGc251ME+E88+xi5gTzh1fewDcwZX/yK2UBb4KO/ARs4r/huYHUDYQW/zCxtYKvjr7H5DVS3GDA5uYHnCTOGZzaQNDBmfngDQxuTVsY2qHdh2NbABt1ezFvs3aA4gBW7XRu0xrBlvb1BZRiLGhob5Gewq+Rpg/Ak1vXcbpCcR4Oq+gaxJZRoq2yQWUWPwusGgQBU6Sw2+I1Bm9p84iuMX3M68R7J13yST9EUG/tIG3s5jjcVbtB2AxRTWwAAAABJRU5ErkJggg==.
        /// </summary>
        internal static string day_night_image {
            get {
                return ResourceManager.GetString("day_night_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACTklEQVR42s3Xb0tTURwH8O0t+NwXIIT1oL+UZYltcw4hNBtairI2793UIYbi0qkLI5HptnvdHIpWskwJbO5f4p+0SM0HGkEvwOe9BdsNvbu733Nr7MidX7js7Jwf53zu7+zJtJoCR3uuAP2L+wPpD7cK57qH6i4PkgDH8sou0yXq08aiBzCXBmhzAjirL1IDvCuHuQGeL34HQKeRHjAeQ8Bw3RUEuN4joMNYSg2YiP2AOc9DAqBvYQ8A7VX0AF8cAS/qryKg990uAUB/Bb44XsHIo2sI6InsAIA10HeAS2AHXpqvI+DZ/DcAMGcA4AmAVw03END99isArHr6Kwgl8QpGG28ioOvNFwA81dF3YCqFHRh7fAsBzrltAFj09IBwEgHepjIEdMxuIeAMOhAmdGCi+TYCHDOfAVB2oVhTUlyU9+G/jn5rtn8ewby/5Q4C2OmN4xz3pQ7XehcB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string floppy_image {
            get {
                return ResourceManager.GetString("floppy_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ibeam {
            get {
                object obj = ResourceManager.GetObject("ibeam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;settings&quot; : 
        ///	{
        ///		&quot;username&quot;							: &quot;{username}&quot;,
        ///		&quot;userid&quot;							: {userid},
        ///		&quot;c_day_Day&quot;							: {&quot;A&quot; : 255, &quot;R&quot;: 211, &quot;G&quot; : 211, &quot;B&quot; : 211},
        ///		&quot;c_night_Day&quot;						: {&quot;A&quot; : 255, &quot;R&quot;: 064, &quot;G&quot; : 064, &quot;B&quot; : 064},
        ///		&quot;c_day_MainBackground&quot;				: {&quot;A&quot; : 255, &quot;R&quot;: 255, &quot;G&quot; : 255, &quot;B&quot; : 255},
        ///		&quot;c_night_MainBackground&quot;			: {&quot;A&quot; : 255, &quot;R&quot;: 169, &quot;G&quot; : 169, &quot;B&quot; : 169},
        ///		&quot;c_day_SelectedDay&quot;					: {&quot;A&quot; : 255, &quot;R&quot;: 000, &quot;G&quot; : 128, &quot;B&quot; : 000},
        ///		&quot;c_night_SelectedDay&quot;				: {&quot;A&quot; : 255, &quot;R&quot;: 255, &quot;G&quot; : 255, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string settings_JSON_Default {
            get {
                return ResourceManager.GetString("settings_JSON_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;settings&quot; : 
        ///	{
        ///		&quot;username&quot;							: &quot;{username}&quot;,
        ///		&quot;userid&quot;							: {userid},
        ///		&quot;c_day_Day&quot;							: {c_day_Day},
        ///		&quot;c_night_Day&quot;						: {c_night_Day},
        ///		&quot;c_day_MainBackground&quot;				: {c_day_MainBackground},
        ///		&quot;c_night_MainBackground&quot;			: {c_night_MainBackground},
        ///		&quot;c_day_SelectedDay&quot;					: {c_day_SelectedDay},
        ///		&quot;c_night_SelectedDay&quot;				: {c_night_SelectedDay},
        ///		&quot;c_day_Sunday&quot;						: {c_day_Sunday},
        ///		&quot;c_night_Sunday&quot;					: {c_night_Sunday},
        ///		&quot;c_day_TextboxBackground&quot;			: {c_day_TextboxBac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string settings_JSON_Template {
            get {
                return ResourceManager.GetString("settings_JSON_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap square {
            get {
                object obj = ResourceManager.GetObject("square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
