//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyDiary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color s_day_DayColor {
            get {
                return ((global::System.Drawing.Color)(this["s_day_DayColor"]));
            }
            set {
                this["s_day_DayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color s_day_SundayColor {
            get {
                return ((global::System.Drawing.Color)(this["s_day_SundayColor"]));
            }
            set {
                this["s_day_SundayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color s_day_MainBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["s_day_MainBackgroundColor"]));
            }
            set {
                this["s_day_MainBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color s_day_TextboxBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["s_day_TextboxBackgroundColor"]));
            }
            set {
                this["s_day_TextboxBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color s_day_TextColor {
            get {
                return ((global::System.Drawing.Color)(this["s_day_TextColor"]));
            }
            set {
                this["s_day_TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color s_night_MainBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["s_night_MainBackgroundColor"]));
            }
            set {
                this["s_night_MainBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color s_night_TextboxBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["s_night_TextboxBackgroundColor"]));
            }
            set {
                this["s_night_TextboxBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color s_night_TextColor {
            get {
                return ((global::System.Drawing.Color)(this["s_night_TextColor"]));
            }
            set {
                this["s_night_TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color s_night_DayColor {
            get {
                return ((global::System.Drawing.Color)(this["s_night_DayColor"]));
            }
            set {
                this["s_night_DayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color s_night_SundayColor {
            get {
                return ((global::System.Drawing.Color)(this["s_night_SundayColor"]));
            }
            set {
                this["s_night_SundayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color s_day_DayTextColor {
            get {
                return ((global::System.Drawing.Color)(this["s_day_DayTextColor"]));
            }
            set {
                this["s_day_DayTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color s_night_DayTextColor {
            get {
                return ((global::System.Drawing.Color)(this["s_night_DayTextColor"]));
            }
            set {
                this["s_night_DayTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool s_textboxLightCursor {
            get {
                return ((bool)(this["s_textboxLightCursor"]));
            }
            set {
                this["s_textboxLightCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_PanelClosed {
            get {
                return ((bool)(this["s_PanelClosed"]));
            }
            set {
                this["s_PanelClosed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool s_textboxLightCursorNightOnly {
            get {
                return ((bool)(this["s_textboxLightCursorNightOnly"]));
            }
            set {
                this["s_textboxLightCursorNightOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_SingleUserMode {
            get {
                return ((bool)(this["s_SingleUserMode"]));
            }
            set {
                this["s_SingleUserMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool s_AskBeforeChange {
            get {
                return ((bool)(this["s_AskBeforeChange"]));
            }
            set {
                this["s_AskBeforeChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string s_SingleUserUsername {
            get {
                return ((string)(this["s_SingleUserUsername"]));
            }
            set {
                this["s_SingleUserUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_NightMode {
            get {
                return ((bool)(this["s_NightMode"]));
            }
            set {
                this["s_NightMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color s_day_SelectedDayColor {
            get {
                return ((global::System.Drawing.Color)(this["s_day_SelectedDayColor"]));
            }
            set {
                this["s_day_SelectedDayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color s_night_SelectedDayColor {
            get {
                return ((global::System.Drawing.Color)(this["s_night_SelectedDayColor"]));
            }
            set {
                this["s_night_SelectedDayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Highlight")]
        public global::System.Drawing.Color s_day_TextSelectionBrush {
            get {
                return ((global::System.Drawing.Color)(this["s_day_TextSelectionBrush"]));
            }
            set {
                this["s_day_TextSelectionBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGoldenrod")]
        public global::System.Drawing.Color s_night_TextSelectionBrush {
            get {
                return ((global::System.Drawing.Color)(this["s_night_TextSelectionBrush"]));
            }
            set {
                this["s_night_TextSelectionBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string s_tbLanguage {
            get {
                return ((string)(this["s_tbLanguage"]));
            }
            set {
                this["s_tbLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_tbSpellCheck {
            get {
                return ((bool)(this["s_tbSpellCheck"]));
            }
            set {
                this["s_tbSpellCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_tbWordWrap {
            get {
                return ((bool)(this["s_tbWordWrap"]));
            }
            set {
                this["s_tbWordWrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_tbAlign {
            get {
                return ((int)(this["s_tbAlign"]));
            }
            set {
                this["s_tbAlign"] = value;
            }
        }
    }
}
